### ISSUE TITLE
Syncing Assets in UE Level with Maya Scene

### ISSUE THREAD

**Issue by SimonBenAnderson** [mgear-dev/ueGear#6]
**A large chunk of this implementation already exists. As this is the first time looking into this feature, a large amount of the tasks below should be completed.**

# Tasks:

## Unreal
- [x] Get selected asset in  Level.
- [x] Export Selected asset.
- [x] Tag asset with asset specific data. [Name, type, object path]
- [x] Find assets in Level.
- [x] Correlate Exported asset to Level Instance.
- [x] Update Transform [Scale, Rotation, Translation]

## Maya
- [x] Import Unreal FBX
- [x] Correlate assets that appear multiple times [Instanced in Unreal]
- [x] Update Transform [Scale, Rotation, Translation]

**Comment by SimonBenAnderson** [comment]
Good progress for day one.

Branches:
https://github.com/mgear-dev/mgear4/tree/ueGear_6
https://github.com/mgear-dev/ueGear/tree/6-syncing-assets-in-ue-level-with-maya-scene

I setup a conversion Matrix, for data going from Maya to Unreal
https://github.com/mgear-dev/mgear4/blob/7c118975bf380b800c9847702df176212965335b/release/scripts/mgear/uegear/utils.py#L1108

Everything has been completed except Maya to Unreal. Hoping to complete that at the start of the week.

**Comment by SimonBenAnderson** [comment]
Just thought of a new use case. 

- [ ] If the user renamed the asset in Unreal, but that asset exists in Maya. Then we should search over every tagged object and replace the ones that have matching UUID.
- [ ] If an asset is updated in Unreal, Box becomes a Sphere, then we would also need to check every instance of the object in Maya. As we currently do not instance object in maya, each is a unique asset

**Comment by SimonBenAnderson** [comment]
The last open box `If an asset is updated in Unreal, Box becomes a Sphere, then we would also need to check every instance of the object in Maya. As we currently do not instance object in maya, each is a unique asset` was left undone, as it it up to the user to select and update the assets they want to update.
